### ISSUE TITLE
Remove WWW-Authenticate-removing code

### ISSUE THREAD

**Issue by ianb** [mozilla/side-view#168]
We should discuss this. Right now it's the only response header we are filtering, and I'm not sure it's worth it (and the performance cost as well). We used to filter several headers, so this one was easy enough to do at the same time.

**Comment by dveditz** [comment]
/cc @pauljt for an additional opinion

I can't remember how locked-down the sidebar view is. If it has to match the currently showing browser page (or origin, at least) then it's not bad at all--but I don't think this is the case. If it isn't allowed to navigate to a different origin once opened that wouldn't be too bad--but I don't think that's the case, either.

To the extent it's just "let me see how my page/site looks in a mobile context" and just an experiment it's probably not a big deal. To the extent that in practice people are going to use it as a second browsing context (issue #1! https://github.com/mozilla/side-view/issues/1) then they're going to wander into places that will end up spoofing them on purpose or accidentally.

Would be tons better if we fixed http auth dialogs to be tab-modal rather than window modal, but I don't know when that ancient bug will get fixed. It's on the eviltraps roadmap though so maybe there's hope.
