### ISSUE TITLE
Cannot navigate in sideview panel.

### ISSUE THREAD

**Issue by samirm** [mozilla/side-view#276]
Cannot do basic things such as go back/forward and refresh.

**Comment by Softvision-CristinaBadescu** [comment]
Thanks for reporting this. We used to have "Home", "Reload" and "Back" buttons in an older Side View version (that it was initially called Tab Split), but due to some issues (https://github.com/mozilla/side-view/issues/63), we dropped out these functionalities, and we no longer have them, at least, for the moment.

**Comment by samirm** [comment]
I see. Perhaps adding them as options in right click could solve both issues?

**Comment by johngruen** [comment]
Yep :( limitations of the API, going to close this for now
