### ISSUE TITLE
Side View page opens in the current page's container

### ISSUE THREAD

**Issue by cpeterso** [mozilla/side-view#281]
I use the [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) extension. Bugzilla is configured to always open in my Work container. Gmail is configured to always open in my Home container. If I open Bugzilla in my main view and then open Gmail in a Side View, the Gmail tab in the Side View uses Bugzilla's Work container instead of my Home container.

I'm not sure if this is a bug or whether it is a bug in the Side View or Multi-Account Containers extension.

**Comment by Softvision-CristinaBadescu** [comment]
Thanks for reporting this. I'm not sure if websites that are assigned to a container, persist their container while are loaded in the sidebar, since they don't appear in the Firefox Multi-Account doorhanger.
 
In order to verify this, I've performed the following steps:
1. Installed both Firefox Multi-Account Containers and Side View webextensions.
2. Assigned Twitter to always open in the "Personal" container and Bugzilla to always open in the "Work" container.
3. Opened Bugzilla in main view and sent a Twitter link to the sidebar.
4. Clicked the Firefox Multi-Account Containers -> "Personal" container and the Twitter page was not displayed there.

However, how did you verify that the Gmail link in the sidebar uses the "Work" container?

From a Facebook Container issue, in [this comment](https://github.com/mozilla/contain-facebook/issues/137#issuecomment-381686662), we have an explanation why a container does not work in the sidebar. 

Here is a screen recording with the behavior: 
![sv and containers](https://user-images.githubusercontent.com/31244235/41235430-7898a7da-6d97-11e8-8cc1-c6998d7b797e.gif)

**Comment by cpeterso** [comment]
> how did you verify that the Gmail link in the sidebar uses the "Work" container?

I have separate personal and work Gmail accounts. When I opened Gmail in the Side View on the Bugzilla page, it opened my work inbox.

**Comment by johngruen** [comment]
Duping to #288
