### ISSUE TITLE
How to Make Side Panel Resizable [Instructions]

### ISSUE THREAD

**Issue by Anduril97** [mozilla/side-view#454]
How to make side panel resizable:
Updated instructions for Feb 2024 (I'm on Firefox version 123)

- Go to about:support
- in Application Basics section find row called Profile Directory, click on Open Directory button
- Close all firefox running instances
- In that folder, find xulstore.json and open it with a text editor
- Find where it says "sidebar-box":{
- inside those brackets look for "style":
- inside this find width: and replace with the following:
width: 50%; max-width: none !important; min-width: 0px !important;

- if you did it correctly it should look like this: "style":"-moz-box-ordinal-group: 3; order: 1; width: 50%; max-width: none !important; min-width: 0px !important;","checked":"true"

- save the file and close, open Firefox and enjoy!

**Comment by NoahTheDuke** [comment]
This doesn't seem to work, sadly.

**Comment by jaredhirsch** [comment]
Thanks for the suggestion. A note of warning: the XUL Store is where Firefox stores the sidebar's width at shutdown, so that it's restored to that same width on the next session. However, userChrome.css is a better solution here, as it's designed to allow a user to make permanent changes to how Firefox is styled. There are a number of explainers around the web on how to remove the sidebar's width limit by adding CSS rules, for instance, https://superuser.com/questions/1276800/customize-the-maximum-width-of-the-firefox-sidebar.
